### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email":"marcoladesnipe@gmail.com",
  "password":"*marcoladesniper"
}

### Find a user with a particular id
GET http://localhost:3000/auth/5

###  Find all users with a given email
GET http://localhost:3000/auth?email=p2arthur@gmail.com

### Update a user by a given id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email":"marcoladesnipe@gmail.com",
  "password":"marilene123"
}

### Delete a user with a given id
DELETE http://localhost:3000/auth/4

###
